api_method.api_method_type.*:
  type: config_entity
  label: 'API HTTP Method type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
