api_endpoint_set.api_endpoint_set_type.*:
  type: config_entity
  label: 'API Endpoint Set type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
