api_param_item.api_param_item_type.*:
  type: config_entity
  label: 'API HTTP Method Parameter Item type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
