api_response_header.api_response_header_type.*:
  type: config_entity
  label: 'API Response Header type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
