api_body_param.api_body_param_type.*:
  type: config_entity
  label: 'API HTTP Method Body Parameter type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
