api_schema.api_schema_type.*:
  type: config_entity
  label: 'API Schema type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
