api_query_param.api_query_param_type.*:
  type: config_entity
  label: 'API HTTP Method Query Parameter type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
