api_license.api_license_type.*:
  type: config_entity
  label: 'API License type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
