api_doc.api_doc_type.*:
  type: config_entity
  label: 'API Documentation type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
