api_global_param.api_global_param_type.*:
  type: config_entity
  label: 'API Global Parameter type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
