api_path_param.api_path_param_type.*:
  type: config_entity
  label: 'API HTTP Method Path Parameter type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
