action.configuration.api_body_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_contact_delete_action:
  type: mapping
  mapping:

action.configuration.api_doc_delete_action:
  type: mapping
  mapping:

action.configuration.api_doc_publish_action:
  type: mapping
  mapping:

action.configuration.api_doc_unpublish_action:
  type: mapping
  mapping:

action.configuration.api_endpoint_delete_action:
  type: mapping
  mapping:

action.configuration.api_endpoint_set_delete_action:
  type: mapping
  mapping:

action.configuration.api_ext_doc_delete_action:
  type: mapping
  mapping:

action.configuration.api_form_data_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_global_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_global_response_delete_action:
  type: mapping
  mapping:

action.configuration.api_global_schema_delete_action:
  type: mapping
  mapping:

action.configuration.api_header_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_info_delete_action:
  type: mapping
  mapping:

action.configuration.api_license_delete_action:
  type: mapping
  mapping:

action.configuration.api_meta_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_method_delete_action:
  type: mapping
  mapping:

action.configuration.api_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_param_item_delete_action:
  type: mapping
  mapping:

action.configuration.api_path_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_query_param_delete_action:
  type: mapping
  mapping:

action.configuration.api_response_delete_action:
  type: mapping
  mapping:

action.configuration.api_response_example_delete_action:
  type: mapping
  mapping:

action.configuration.api_response_header_delete_action:
  type: mapping
  mapping:

action.configuration.api_response_set_delete_action:
  type: mapping
  mapping:

action.configuration.api_schema_delete_action:
  type: mapping
  mapping:

action.configuration.api_tag_delete_action:
  type: mapping
  mapping:

action.configuration.api_version_tag_delete_action:
  type: mapping
  mapping:

views.field.api_body_param_bulk_form:
  type: views_field_bulk_form

views.field.api_contact_bulk_form:
  type: views_field_bulk_form

views.field.api_doc_bulk_form:
  type: views_field_bulk_form

views.field.api_endpoint_bulk_form:
  type: views_field_bulk_form

views.field.api_endpoint_set_bulk_form:
  type: views_field_bulk_form

views.field.api_ext_doc_bulk_form:
  type: views_field_bulk_form

views.field.api_form_data_param_bulk_form:
  type: views_field_bulk_form

views.field.api_global_param_bulk_form:
  type: views_field_bulk_form

views.field.api_global_response_bulk_form:
  type: views_field_bulk_form

views.field.api_header_param_bulk_form:
  type: views_field_bulk_form

views.field.api_global_schema_bulk_form:
  type: views_field_bulk_form

views.field.api_info_bulk_form:
  type: views_field_bulk_form

views.field.api_license_bulk_form:
  type: views_field_bulk_form

views.field.api_meta_param_bulk_form:
  type: views_field_bulk_form

views.field.api_method_bulk_form:
  type: views_field_bulk_form

views.field.api_param_bulk_form:
  type: views_field_bulk_form

views.field.api_param_item_bulk_form:
  type: views_field_bulk_form

views.field.api_path_param_bulk_form:
  type: views_field_bulk_form

views.field.api_query_param_bulk_form:
  type: views_field_bulk_form

views.field.api_response_bulk_form:
  type: views_field_bulk_form

views.field.api_response_example_bulk_form:
  type: views_field_bulk_form

views.field.api_response_header_bulk_form:
  type: views_field_bulk_form

views.field.api_response_set_bulk_form:
  type: views_field_bulk_form

views.field.api_schema_bulk_form:
  type: views_field_bulk_form

views.field.api_tag_bulk_form:
  type: views_field_bulk_form

views.field.api_version_tag_bulk_form:
  type: views_field_bulk_form
