<?php
/**
 * Devportal Standard - FAQ module for Drupal.
 *
 * Copyright (C) 2018 PRONOVIX GROUP BVBA.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */

use Drupal\Core\Form\FormStateInterface;

function dp_faq_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  if ($form["#id"] === 'views-exposed-form-devportal-faq-page-1') {
    $form['#attached']['library'][] = 'dp_faq/faq';
  }
}
