devportal_repo_sync.config:
  type: config_object
  label: 'Repo Sync'
  mapping:
    account:
      type: string
      label: Account
    secret:
      type: string
      label: Secret
    service:
      type: string
      label: Service
    baseurl:
      type: string
      label: Base url
