devportal_repo_sync.repo_account.*:
  type: config_entity
  label: 'Repository account'
  mapping:
    label:
      type: label
      label: 'Label'
    provider:
      type: string
      label: 'Provider'
    method:
      type: string
      label: 'Method'
    identifier:
      type: string
      label: 'Identifier'
    secret:
      type: string
      label: 'Secret'

devportal_repo_sync.repo_import.*:
  type: config_entity
  label: 'Repository import'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    repo_account_id:
      type: uuid
      label: 'Repo Account ID'
    repository:
      type: string
      label: 'Full repository name'
    version:
      type: string
      label: 'Branch or tag'
    directories:
      type: sequence
      label: 'Directories'
    fileTypes:
      type: sequence
      sequence:
        type: mapping
        mapping:
          extensions:
            type: sequence
            label: 'File extension groups to import'
            sequence:
              type: string
          converterPlugin:
            type: string
            label: 'Machine names of the plugins that converts file contents to html'
    stage:
      type: boolean
      label: 'Publish changes automatically'
    changed:
      type: timestamp
      label: 'Latest change'
    webhook:
      type: string
      label: 'Webhook hash'
    bid:
      type: integer
      label: 'Book ID.'
    refs:
      type: sequence
      sequence:
        type: integer

devportal_repo_sync.import:
  type: config_object
  mapping:
    raw_files:
      type: string
    account:
      type: mapping
      mapping:
        default_provider:
          type: string
        default_method:
          type: string
        restrict_methods:
          type: boolean
    webhook:
      type: mapping
      mapping:
        enabled:
          type: boolean
        ping:
          type: string
    cache:
      type: boolean
    files:
      type: sequence
      sequence:
        type: mapping
        mapping:
          extensions:
            type: sequence
            sequence:
              type: string
          label:
            type: string
    help:
      type: mapping
      mapping:
        auth:
          type: sequence
          sequence:
            type: string

