<?php

namespace Drupal\devportal_api_entities\Entity;

use Drupal\Core\Entity\EntityChangedTrait;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\RevisionableContentEntityBase;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\devportal_api_entities\APIResponseSetInterface;
use Drupal\devportal_api_reference\Traits\APIRefTrait;
use Drupal\devportal_api_entities\Traits\AutoLabelTrait;
use Drupal\devportal_api_entities\Traits\APIVersionTagRefTrait;
use Drupal\devportal\Traits\URLRouteParametersTrait;;
use Drupal\devportal_api_entities\Traits\VendorExtensionTrait;

/**
 * Defines the API Response Set entity class.
 *
 * @ContentEntityType(
 *   id = "api_response_set",
 *   label = @Translation("API Response Set"),
 *   handlers = {
 *     "storage" = "Drupal\devportal_api_entities\APIResponseSetStorage",
 *     "list_builder" = "Drupal\devportal_api_entities\APIResponseSetListBuilder",
 *     "view_builder" = "Drupal\devportal\DevportalContentEntityViewBuilder",
 *     "views_data" = "Drupal\devportal_api_entities\APIResponseSetViewsData",
 *     "form" = {
 *       "default" = "Drupal\devportal\Form\DevportalContentEntityForm",
 *       "add" = "Drupal\devportal\Form\DevportalContentEntityForm",
 *       "edit" = "Drupal\devportal\Form\DevportalContentEntityForm",
 *       "delete" = "Drupal\devportal\Form\DevportalContentEntityDeleteForm",
 *     },
 *     "inline_form" = "Drupal\devportal_api_entities\Form\DevportalInlineForm",
 *     "route_provider" = {
 *       "html" = "Drupal\devportal_api_entities\APIResponseSetHtmlRouteProvider",
 *     },
 *     "access" = "Drupal\devportal_api_entities\APIResponseSetAccessControlHandler",
 *     "translation" = "Drupal\devportal_api_entities\APIResponseSetTranslationHandler",
 *   },
 *   admin_permission = "administer api response sets",
 *   fieldable = TRUE,
 *   base_table = "api_response_set",
 *   data_table = "api_response_set_field_data",
 *   field_ui_base_route = "entity.api_response_set_type.edit_form",
 *   entity_keys = {
 *     "id" = "id",
 *     "bundle" = "type",
 *     "uuid" = "uuid",
 *     "revision" = "vid",
 *     "langcode" = "langcode",
 *     "label" = "auto_label",
 *   },
 *   api_extra_info = {
 *     "auto_label" = {
 *       "auto_label" = "auto_label",
 *       "autogenerated_label" = "autogenerated_label",
 *     },
 *     "api_ref" = "api_ref",
 *     "api_version_tag" = "api_version_tag",
 *     "vendor_extension" = "extensions",
 *   },
 *   bundle_entity_type = "api_response_set_type",
 *   bundle_label = @Translation("API Response Set type"),
 *   revision_table = "api_response_set_revision",
 *   revision_data_table = "api_response_set_field_revision",
 *   show_revision_ui = TRUE,
 *   revision_metadata_keys = {
 *     "revision_user" = "revision_user",
 *     "revision_created" = "revision_created",
 *     "revision_log_message" = "revision_log",
 *   },
 *   links = {
 *     "canonical" = "/api_response_set/{api_response_set}",
 *     "add-page" = "/api_response_set/add",
 *     "add-form" = "/api_response_set/add/{api_response_set_type}",
 *     "edit-form" = "/api_response_set/{api_response_set}/edit",
 *     "delete-form" = "/api_response_set/{api_response_set}/delete",
 *     "collection" = "/admin/content/api_response_set",
 *     "version-history" = "/api_response_set/{api_response_set}/revisions",
 *     "revision" = "/api_response_set/{api_response_set}/revisions/{api_response_set_revision}/view",
 *     "revision_revert" = "/api_response_set/{api_response_set}/revisions/{api_response_set_revision}/revert",
 *     "revision_delete" = "/api_response_set/{api_response_set}/revisions/{api_response_set_revision}/delete",
 *     "multiple_delete_confirm" = "/admin/content/api_response_set/delete",
 *     "translation_revert" = "/api_response_set/{api_response_set}/revisions/{api_response_set_revision}/revert/{langcode}",
 *   },
 *   translatable = TRUE,
 * )
 */
class APIResponseSet extends RevisionableContentEntityBase implements APIResponseSetInterface {

  use EntityChangedTrait;
  use AutoLabelTrait;
  use APIRefTrait;
  use APIVersionTagRefTrait;
  use VendorExtensionTrait;
  use URLRouteParametersTrait;

  /**
   * {@inheritdoc}
   */
  public function preSave(EntityStorageInterface $storage) {
    parent::preSave($storage);

    // Generate auto label.
    $this->autoLabelPreSave();
  }

  /**
   * {@inheritdoc}
   */
  public function preSaveRevision(EntityStorageInterface $storage, \stdClass $record) {
    parent::preSaveRevision($storage, $record);

    if (!$this->isNewRevision() && isset($this->original) && (!isset($record->revision_log) || $record->revision_log === '')) {
      // If we are updating an existing APIResponseSet without adding a new
      // revision, we need to make sure $entity->revision_log is reset whenever
      // it is empty. Therefore, this code allows us to avoid clobbering an
      // existing log entry with an empty one.
      $record->revision_log = $this->original->revision_log->value;
    }
  }

  /**
   * {@inheritdoc}
   */
  public function generateAutoLabel() {
    /** @var \Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem $api_method_first */
    $api_method_first = $this->get('api_method')->first();
    /** @var \Drupal\Core\Entity\Plugin\DataType\EntityReference $api_method_first_entity */
    $api_method_first_entity = $api_method_first->get('entity');
    /** @var \Drupal\devportal_api_entities\Entity\APIMethod $api_method */
    $api_method = $api_method_first_entity->getTarget()->getValue();

    return t('Responses of @api_method', ['@api_method' => $api_method->label()]);
  }

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {
    /** @var \Drupal\Core\Field\BaseFieldDefinition[] $fields */
    $fields = parent::baseFieldDefinitions($entity_type);

    // Add the auto label field.
    $fields += static::autoLabelBaseFieldDefinitions($entity_type);

    // Add the vendor extension fields.
    $fields += static::vendorExtensionBaseFieldDefinitions($entity_type);

    // Add the API Reference field.
    $fields += static::apiRefBaseFieldDefinitions($entity_type);
    $fields['api_ref']->setDescription(t('API Reference referenced from API Response Set.'));

    // Add the API Version Tag field.
    $fields += static::apiVersionTagBaseFieldDefinitions($entity_type);
    $fields['api_version_tag']->setDescription(t('API Version Tag referenced from API Response Set.'));

    $fields['id']->setDescription(t('The API Response Set ID.'));

    $fields['uuid']->setDescription(t('The API Response Set UUID.'));

    $fields['vid']->setDescription(t('The API Response Set revision ID.'));

    $fields['langcode']->setDescription(t('The API Response Set language code.'));

    $fields['api_method'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('API HTTP Method'))
      ->setRequired(TRUE)
      ->setRevisionable(TRUE)
      ->setDescription(t('API HTTP Method referenced from API Response Set.'))
      ->setSettings([
        'target_type' => 'api_method',
        'handler' => 'default',
        'handler_settings' => [
          'sort' => [
            'field' => '_none',
          ],
          'auto_create' => FALSE,
          'auto_create_bundle' => '',
        ],
      ])
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'entity_reference_label',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'inline_entity_form_complex',
        'weight' => 5,
        'settings' => [
          'form_mode' => 'default',
          'override_labels' => TRUE,
          // @FIXME Should these use $this->>t()?
          'label_singular' => 'method',
          'label_plural' => 'methods',
          'allow_new' => TRUE,
          'allow_existing' => TRUE,
          'match_operator' => 'CONTAINS',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Changed'))
      ->setDescription(t('The time that the API Response Set was last edited.'))
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE);

    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public function label() {
    $label = parent::label();
    if (empty($label)) {
      $label = $this->generateAutoLabel();
    }
    return $label;
  }

}
